name: Publish to NPM

on:
  release:
    types: [created]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                node-version: 20
                registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run build
            - name: Publish to NPM
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
